### PR TITLE
fix impcomplete issue

### PR DESCRIPTION
**Pull request by mitnk**
This PR is a patch to https://github.com/meh/rust-terminfo/pull/13 so that it can make all test pass.

### CODE REVIEW

**Comment by mitnk** [comment]
Hi @Geal Could you have a check on this PR when you got time. Thanks

**Comment by mitnk** [comment]
Pinging on this - If we merge this (if you are correct according to you) to your branch, the CI in [original PR](https://github.com/meh/rust-terminfo/pull/13) should pass - Then that PR can be merged :-)

Sorry for bothering.

**Comment by Geal** [comment]
thanks, nice fix

**Comment by mitnk** [comment]
Thanks!

**Pull request merged**
